version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: placement_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  backend:
    build: .
    container_name: placement_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/PlacementPortal
    depends_on:
      - mongo
    volumes:
      - .:/app
volumes:
  mongo_data:
